version: '3.7'

services:

  web:
    build:
      context: ./nginx
    command: bash -c "nginx && php-fpm"
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    environment:
        XDEBUG_CONFIG: remote_host=109.41.66.107

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8800:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql
